FROM ghcr.io/puppeteer/puppeteer:24.22.3 
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable \
    NODE_ENV=production
WORKDIR /usr/src/app
COPY package*.json ./
# Run install as root
USER root
RUN npm install
# Switch back to Puppeteer user if needed
USER pptruser
COPY . .
CMD ["node", "index.js"]